- src/CrowdinApiClient/Http/Client/CurlHttpClient.php
If curl adapter is set the api is called twice and if need to create a new object via the api it causes creating duplicated objects.
> Curl adapter creates duplicate requests

- src/CrowdinApiClient/Model/GlossaryExport.php
- src/CrowdinApiClient/Model/GlossaryImport.php
- src/CrowdinApiClient/Model/PreTranslation.php
- src/CrowdinApiClient/Model/Report.php
- src/CrowdinApiClient/Model/TranslationMemoryExport.php
- src/CrowdinApiClient/Model/TranslationMemoryImport.php
- tests/CrowdinApiClient/Api/Enterprise/GlossaryApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/ReportApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/TranslationApiTest.php
- tests/CrowdinApiClient/Api/GlossaryApiTest.php
- tests/CrowdinApiClient/Api/ReportApiTest.php
- tests/CrowdinApiClient/Api/TranslationApiTest.php
- tests/CrowdinApiClient/Api/TranslationMemoryApiTest.php
- tests/CrowdinApiClient/Model/GlossaryExportTest.php
- tests/CrowdinApiClient/Model/GlossaryImportImportTest.php
- tests/CrowdinApiClient/Model/PreTranslationTest.php
- tests/CrowdinApiClient/Model/ReportTest.php
- tests/CrowdinApiClient/Model/TranslationMemoryExportTest.php
- tests/CrowdinApiClient/Model/TranslationMemoryImportTest.php
removed 'eta' parameters from all Reports, Import and Export response model: GlossaryExport, GlossaryImport, PreTranslation, Report, TranslationMemoryExport, TranslationMemoryImport.
> remove eta from reports, imports and exports

- composer.json
This PR adds package discovery for Laravel.
I noticed while installing this into a Laravel project that while this package supports Laravel and has a service provider for it, it was never added to the `extra` key in the `composer.json` file.
For more information regarding this please refer to the [Package Discovery section of the Laravel docs](https://laravel.com/docs/8.x/packages#package-discovery).
> Add package discovery for Laravel

- src/CrowdinApiClient/Api/StorageApi.php
- tests/CrowdinApiClient/Api/StorageApiTest.php
Using base class SplFileInfo for creating Storage to decrease dependency only for required methods. 
It allows also using Symfony Finder component easier.
> Use base class SplFileInfo instead of SplFileObject

- src/CrowdinApiClient/Collection.php
While updating our PHP version to 8.1, we got deprecation warnings regarding the use of `IteratorAggregate`. This just suppresses those warnings for now.
Connects: https://github.com/crowdin/crowdin-api-client-php/issues/124
> Collection: Suppress deprecations for PHP 8.1

- phpunit.xml
- src/CrowdinApiClient/Collection.php
- src/CrowdinApiClient/CollectionIterator.php
- tests/CrowdinApiClient/CollectionIteratorTest.php
Whoops, I seem to have missed a few of these accidentally in https://github.com/crowdin/crowdin-api-client-php/pull/125. Sorry about that. This fixes (or suppresses) the incompatible type warnings.
Connects: https://github.com/crowdin/crowdin-api-client-php/issues/124
> Collection: Fix php 8.1 warnings

- src/CrowdinApiClient/Api/GlossaryApi.php
- tests/CrowdinApiClient/Api/Enterprise/GlossaryApiTest.php
- tests/CrowdinApiClient/Api/GlossaryApiTest.php
Fixing the download glossary method to include the exportId as per the API documentation
> Updating the glossary download 

- src/CrowdinApiClient/Api/GlossaryApi.php
- tests/CrowdinApiClient/Api/Enterprise/GlossaryApiTest.php
- tests/CrowdinApiClient/Api/GlossaryApiTest.php
Adding `exportFields` parameter to the glossary export method, to reflect the API - https://developer.crowdin.com/api/v2/#operation/api.glossaries.exports.post
> feat: Add glossary exportfields

- src/CrowdinApiClient/Api/AbstractApi.php
- tests/CrowdinApiClient/Api/AbstractTestApi.php
- tests/CrowdinApiClient/Api/BranchApiTest.php
- tests/CrowdinApiClient/Api/BundleApiTest.php
- tests/CrowdinApiClient/Api/DirectoryApiTest.php
- tests/CrowdinApiClient/Api/DistributionApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/AbstractTestApi.php
- tests/CrowdinApiClient/Api/Enterprise/FileApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/GlossaryApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/MachineTranslationEngineApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/ProjectApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/StringTranslationApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/TaskApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/TeamApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/TranslationApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/UserApiTest.php
- tests/CrowdinApiClient/Api/FileApiTest.php
- tests/CrowdinApiClient/Api/GlossaryApiTest.php
- tests/CrowdinApiClient/Api/LabelApiTest.php
- tests/CrowdinApiClient/Api/MachineTranslationEngineApiTest.php
- tests/CrowdinApiClient/Api/ProjectApiTest.php
- tests/CrowdinApiClient/Api/ScreenshotApiTest.php
- tests/CrowdinApiClient/Api/SourceStringApiTest.php
- tests/CrowdinApiClient/Api/StringCommentApiTest.php
- tests/CrowdinApiClient/Api/StringTranslationApiTest.php
- tests/CrowdinApiClient/Api/TaskApiTest.php
- tests/CrowdinApiClient/Api/TranslationApiTest.php
- tests/CrowdinApiClient/Api/TranslationMemoryApiTest.php
- tests/CrowdinApiClient/Api/WebhookApiTest.php
This addresses the issues in `AbstractTestApi::mockRequest` assertions and resolves the missed issues with many unit tests. Primarily the tests themselves have issues where they pass in an array but `mockRequest` asserts against a json string. Additionally when a `$params['response']` was unset, `AbstractTestApi::mockRequest` would return `null` which was causing `PHP Notices` that the GitHub Actions configuration was hiding.
There was one issue with `AbstractApi::_delete` that was detected with the fixed assertions where `$params` was being passed to `Crowdin::apiRequest` without being wrapped into a request `$options`.
Fixes #149
> fix: Fix AbstractTestApi::mockRequest assertions

- .github/workflows/docs.yml
Tested new command locally
```shell
$ docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 run -d src -t .phpdoc/build
phpDocumentor 3.4.1-dev-master+8b2bec0
Parsing files
1/120 [>---------------------------]   0%
12/120 [==>-------------------------]  10%
24/120 [=====>----------------------]  20%
36/120 [========>-------------------]  30%
48/120 [===========>----------------]  40%
60/120 [==============>-------------]  50%
72/120 [================>-----------]  60%
84/120 [===================>--------]  70%
96/120 [======================>-----]  80%
108/120 [=========================>--]  90%
120/120 [============================] 100%
Applying transformations (can take a while)
All done in 7 seconds!
```
Fixes #155
> fix: Add missing phpdoc `run` command

- src/CrowdinApiClient/Model/Project.php
- tests/CrowdinApiClient/Api/ProjectApiTest.php
- tests/CrowdinApiClient/Model/ProjectTest.php
Adds `Project:: qaChecksIgnorableCategories` property. As the API calls themselves use unstructured array, I've added the expected array and json to `ProjectTest` & `ProjectApiTest` to provide expected example usage.
Closes #123
> feat: Add Projects `qaChecksIgnorableCategories` support

- src/CrowdinApiClient/Api/StringsExporterSettingApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/StringsExporterSetting.php
- tests/CrowdinApiClient/Api/StringsExporterSettingApiTest.php
- tests/CrowdinApiClient/Model/StringsExporterSettingTest.php
This pull request will add Crowdin Strings Exporter settings API endpoints in the PHP API client.
Fixes: #147
> feat: Add Strings Exporter Settings API #147

- src/CrowdinApiClient/Api/FileApi.php
- src/CrowdinApiClient/Model/File.php
- tests/CrowdinApiClient/Api/FileApiTest.php
- tests/CrowdinApiClient/Model/FileTest.php
> feat: translation context field to Files API

- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Http/ResponseErrorHandlerInterface.php
- src/CrowdinApiClient/ModelCollection.php
This removes the `@internal` doctag property for `ResponseErrorHandlerInterface` & `ModelCollection`, both which are used by the consumers of the library. In addition, the `Crowdin` properties doctags have been corrected.
Resolves #187
> fix: Remove @internal for exposed classes

- src/CrowdinApiClient/Api/StringTranslationApi.php
Updates the `StringTranslationApi` doctags to document the new parameters. No other code changes were found to be needed as the parameters are not in the response objects.
Closes #175
> feat: List Language Translations API: support new parameters

- src/CrowdinApiClient/Api/TranslationApi.php
Removes all occurrences of `markAddedTranslationsAsDone` which is only found in doctags.
Closes #177
> feat: Remove the `markAddedTranslationsAsDone` parameter

- .gitignore
- src/CrowdinApiClient/Api/SourceStringApi.php
- tests/CrowdinApiClient/Api/SourceStringApiTest.php
> feat(api): added endpoint for batch source string editing

- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Http/Client/GuzzleHttpClient.php
PHP 8.4 deprecates implicitly allowing nullable param types. This fixes the issues in this package.
Closes: https://github.com/crowdin/crowdin-api-client-php/issues/212
> fix: php 8.4 warnings

- src/CrowdinApiClient/Api/TranslationMemoryApi.php
- src/CrowdinApiClient/Model/TranslationMemorySegment.php
- src/CrowdinApiClient/Model/TranslationMemorySegmentRecord.php
- tests/CrowdinApiClient/Api/TranslationMemoryApiTest.php
- tests/CrowdinApiClient/Model/TranslationMemorySegmentRecordTest.php
- tests/CrowdinApiClient/Model/TranslationMemorySegmentTest.php
Adds support for the following Translation Memory Segments API endpoints
- [List TM Segments](https://developer.crowdin.com/api/v2/#operation/api.tms.segments.getMany)
- [Create TM Segment](https://developer.crowdin.com/api/v2/#operation/api.tms.segments.post)
- [Get TM Segment](https://developer.crowdin.com/api/v2/#operation/api.tms.segments.get)
- [Delete TM Segment](https://developer.crowdin.com/api/v2/#operation/api.tms.segments.delete)
Closes #128
> feat: Add the Translation Memory Segments API support

- src/CrowdinApiClient/Api/Enterprise/StringCorrectionApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/StringCorrection.php
- tests/CrowdinApiClient/Api/Enterprise/StringCorrectionApiTest.php
- tests/CrowdinApiClient/Model/StringCorrectionTest.php
Adds support for the following String Corrections API endpoints
- [List Corrections](https://support.crowdin.com/developer/enterprise/api/v2/#tag/String-Corrections/operation/api.projects.corrections.getMany)
- [Add Correction](https://support.crowdin.com/developer/enterprise/api/v2/#tag/String-Corrections/operation/api.projects.corrections.post)
- [Delete Corrections](https://support.crowdin.com/developer/enterprise/api/v2/#tag/String-Corrections/operation/api.projects.corrections.deleteMany)
- [Get Correction](https://support.crowdin.com/developer/enterprise/api/v2/#tag/String-Corrections/operation/api.projects.corrections.get)
- [Restore Correction](https://support.crowdin.com/developer/enterprise/api/v2/#tag/String-Corrections/operation/api.projects.corrections.put)
- [Delete …
> feat: Add support for new String Corrections API
