crowdin/crowdin-api-client-php

- .gitignore
- ci/basic.yml
- ci/templates/jobs.yml
- ci/tests-ubuntu.yml
- phpunit.xml
- run tests
- integrate with codecov.io
> Improve CI

- src/CrowdinApiClient/Api/DistributionApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/Distribution.php
- src/CrowdinApiClient/Model/DistributionRelease.php
- tests/CrowdinApiClient/Api/DistributionApiTest.php
- tests/CrowdinApiClient/CrowdinTest.php
- tests/CrowdinApiClient/Model/DistributionReleaseTest.php
- tests/CrowdinApiClient/Model/DistributionTest.php
added Distribution API, +tests
> added Distribution API, +tests

- src/CrowdinApiClient/Api/Enterprise/FileApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/Enterprise/ReviewedSourceFileBuild.php
- tests/CrowdinApiClient/Api/Enterprise/FileApiTest.php
- tests/CrowdinApiClient/CrowdinTest.php
Add export reviewed source
https://support.crowdin.com/enterprise/api/#operation/api.projects.strings.reviewed-builds.post
> Add export reviewed source

- src/CrowdinApiClient/Model/SourceString.php
- tests/CrowdinApiClient/Api/SourceStringApiTest.php
- tests/CrowdinApiClient/Model/SourceStringTest.php
remove plurals from Source String
> remove plurals from Source String

- src/CrowdinApiClient/Api/TranslationApi.php
- tests/CrowdinApiClient/Api/TranslationApiTest.php
added export project translation, + unit test
> added export project translation, + unit test

- src/CrowdinApiClient/Model/File.php
- tests/CrowdinApiClient/Api/FileApiTest.php
- tests/CrowdinApiClient/Model/FileTest.php
File model changes: revision => revisionId; added path
> File model changes: revision => revisionId; added path

- src/CrowdinApiClient/Api/TranslationMemoryApi.php
- tests/CrowdinApiClient/Api/TranslationMemoryApiTest.php
Translation memory: add Clear TM method
> Translation memory: add Clear TM method

- src/CrowdinApiClient/Api/StringTranslationApi.php
- src/CrowdinApiClient/Api/TaskApi.php
- src/CrowdinApiClient/Api/TranslationStatusApi.php
- tests/CrowdinApiClient/Api/Enterprise/StringTranslationApiTest.php
- tests/CrowdinApiClient/Api/StringTranslationApiTest.php
- tests/CrowdinApiClient/Api/TaskApiTest.php
- tests/CrowdinApiClient/Api/TranslationStatusApiTest.php
change endpoints according to crowdin api.v2 changes
> change endpoints according to crowdin api.v2 changes

- composer.json
- src/CrowdinApiClient/Api/TranslationApi.php
> - fix upload translations

- src/CrowdinApiClient/Api/IssueApi.php
- src/CrowdinApiClient/Api/StringCommentApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/StringComment.php
- tests/CrowdinApiClient/Api/StringCommentApiTest.php
- tests/CrowdinApiClient/Model/StringCommentTest.php
added StringComment model, StringCommentApi, deprecated all methods in  IssueApi
> added StringComment model, StringCommentApi, deprecated IssueApi

- src/CrowdinApiClient/Model/File.php
- tests/CrowdinApiClient/Api/FileApiTest.php
- tests/CrowdinApiClient/Model/FileTest.php
added excludedTargetLanguages + tests
> files: excludedTargetLanguages

- src/CrowdinApiClient/Model/Webhook.php
- tests/CrowdinApiClient/Api/WebhookApiTest.php
added batchingEnabled to webhook model, tests
> added batching enabled to webhook model, tests

- CONTRIBUTING.md
- composer.json
- src/CrowdinApiClient/Api/Enterprise/UserApi.php
- src/CrowdinApiClient/Model/Enterprise/ProjectTeamMemberResource.php
- src/CrowdinApiClient/Model/Project.php
- src/CrowdinApiClient/Model/SourceString.php
- tests/CrowdinApiClient/Api/Enterprise/ProjectApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/UserApiTest.php
- tests/CrowdinApiClient/Api/ProjectApiTest.php
- tests/CrowdinApiClient/Model/Enterprise/ProjectTeamMemberResourceTest.php
- tests/CrowdinApiClient/Model/ProjectTest.php
- tests/CrowdinApiClient/Model/SourceStringTest.php
- Update Project model
- Update SourceString model
- Update Enterprise Project Members API
> API Updates

- src/CrowdinApiClient/Api/LabelApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/Label.php
- tests/CrowdinApiClient/Api/LabelApiTest.php
- tests/CrowdinApiClient/CrowdinTest.php
- tests/CrowdinApiClient/Model/LabelTest.php
- Adds Label Model Class
- Adds LabelApi
- Adds Tests For LabelApi and Label Model
> Add labels API

- src/CrowdinApiClient/Api/Enterprise/UserApi.php
- tests/CrowdinApiClient/Api/Enterprise/UserApiTest.php
> Added Enterprise user endpoints

- src/CrowdinApiClient/Api/BundleApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/Bundle.php
- tests/CrowdinApiClient/Api/BundleApiTest.php
- tests/CrowdinApiClient/CrowdinTest.php
- tests/CrowdinApiClient/Model/BundleTest.php
> Added bundle endpoints

- src/CrowdinApiClient/Api/DistributionApi.php
- src/CrowdinApiClient/Model/Distribution.php
- tests/CrowdinApiClient/Api/DistributionApiTest.php
- tests/CrowdinApiClient/Model/DistributionTest.php
> Updated distribution model and endpoints to match documentation

- src/CrowdinApiClient/Api/Enterprise/MachineTranslationEngineApi.php
- src/CrowdinApiClient/Api/MachineTranslationEngineApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/MachineTranslation.php
- tests/CrowdinApiClient/Api/Enterprise/MachineTranslationEngineApiTest.php
- tests/CrowdinApiClient/Api/MachineTranslationEngineApiTest.php
- tests/CrowdinApiClient/CrowdinTest.php
- tests/CrowdinApiClient/Model/MachineTranslationTest.php
> New Translate via MT endpoint

- src/CrowdinApiClient/Api/TranslationApi.php
- src/CrowdinApiClient/Model/TranslationProjectDirectory.php
- tests/CrowdinApiClient/Api/Enterprise/TranslationApiTest.php
> feat(directory): Added Project build directory endpoint

- .php-cs-fixer.dist.php
- composer.json
- tests/CrowdinApiClient/Api/TranslationApiTest.php
- tests/CrowdinApiClient/Api/TranslationStatusApiTest.php
> Upgrade php cs fixer

- src/CrowdinApiClient/CollectionIterator.php
Fix `CollectionIterator::next()` return type.
> Fix CollectionIterator PhpDoc

- src/CrowdinApiClient/Collection.php
- tests/CrowdinApiClient/CollectionTest.php
> Add `CrowdinApiClient\Collection::__toArray()` method

- src/CrowdinApiClient/Model/TranslationMemory.php
- tests/CrowdinApiClient/Api/TranslationMemoryApiTest.php
- tests/CrowdinApiClient/Model/TranslationMemoryTest.php
The objective of this PR is to remove the defaultProjectId and add defaultProjectIds.
It's related with this issue: https://github.com/crowdin/crowdin-api-client-php/issues/121
> Change defaultProjectId to defaultProjectIds

- src/CrowdinApiClient/Model/Distribution.php
- tests/CrowdinApiClient/Api/DistributionApiTest.php
- tests/CrowdinApiClient/Model/DistributionTest.php
> feat: distributions API updates

- src/CrowdinApiClient/Api/Enterprise/NotificationApi.php
- src/CrowdinApiClient/Api/NotificationApi.php
- src/CrowdinApiClient/Crowdin.php
- tests/CrowdinApiClient/Api/Enterprise/NotificationApiTest.php
- tests/CrowdinApiClient/Api/NotificationApiTest.php
This MR allow to send notifications to authenticated user, projects members or organization members
Fix: https://github.com/crowdin/crowdin-api-client-php/issues/142
> feat: Add support for the Notifications API

- tests/CrowdinApiClient/Api/Enterprise/NotificationApiTest.php
- tests/CrowdinApiClient/Api/NotificationApiTest.php
The PR (https://github.com/crowdin/crowdin-api-client-php/pull/150) broke test of https://github.com/crowdin/crowdin-api-client-php/pull/152
This PR fix tests for the merged code.
> chore: fix notifications tests

- src/CrowdinApiClient/Api/LabelApi.php
- tests/CrowdinApiClient/Api/LabelApiTest.php
This MR allows assign and unassigned label from screenshots
Fix: https://github.com/crowdin/crowdin-api-client-php/issues/132
> feat: Add the Screenshot Labels management APIs

- src/CrowdinApiClient/Api/TaskApi.php
- src/CrowdinApiClient/Model/TaskSettingsTemplate.php
- tests/CrowdinApiClient/Api/TaskApiTest.php
- tests/CrowdinApiClient/Model/TaskSettingsTemplateTest.php
> feat(task-settings-template): Added Task Settings Template endpoints

- src/CrowdinApiClient/Api/OrganizationWebhookApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/OrganizationWebhook.php
- tests/CrowdinApiClient/Api/OrganizationWebhookApiTest.php
- tests/CrowdinApiClient/Model/OrganizationWebhookTest.php
> feat(organization-webhook): Added Organization webhook model and API

- .gitignore
- src/CrowdinApiClient/Api/Enterprise/GroupApi.php
- src/CrowdinApiClient/Api/Enterprise/ReportApi.php
- src/CrowdinApiClient/Crowdin.php
- tests/CrowdinApiClient/Api/Enterprise/GroupApiTest.php
- tests/CrowdinApiClient/Api/Enterprise/ReportApiTest.php
- tests/CrowdinApiClient/Api/ReportApiTest.php
- tests/CrowdinApiClient/CrowdinTest.php
> feat: Report API changes

- src/CrowdinApiClient/Api/StringTranslationApi.php
@andrii-bodnar Could you please reveiw this?
> feat: Strings translations APIs: add new parameters support #166

- src/CrowdinApiClient/Api/Enterprise/ReportArchiveApi.php
- src/CrowdinApiClient/Api/ReportArchiveApi.php
- src/CrowdinApiClient/Crowdin.php
- src/CrowdinApiClient/Model/ReportArchive.php
- src/CrowdinApiClient/Model/ReportArchiveExport.php
- tests/CrowdinApiClient/Api/Enterprise/ReportArchiveApiTest.php
- tests/CrowdinApiClient/Api/ReportArchiveApiTest.php
> feat: Added Report Archives API endpoints

- src/CrowdinApiClient/Model/LanguageTranslation.php
> fix: LanguageTranslation return types

- src/CrowdinApiClient/Model/Screenshot.php
- tests/CrowdinApiClient/Api/ScreenshotApiTest.php
- tests/CrowdinApiClient/Model/ScreenshotTest.php
Adds `Screenshot::labelIds`
Closes #169
> feat: Screenshots APIs: add the `labelIds` parameter support
